### ISSUE TITLE
Encypted TiddlyWiki Error

### ISSUE THREAD

**Issue by ghost** [JulianSchuette/tiddlysnip#2]
Would it be possible allow the plugin to access an encrypted TW if the password is set in options? Currently I get an error saying it's not a valid TW file if I try to snip something.

**Comment by JulianSchuette** [comment]
It depends. There are various plugins for encrypting tiddlers and we would need to have a look at your specific one.

**Comment by ghost** [comment]
I'm referring to the built in TW5 encryption.

**Comment by JulianSchuette** [comment]
Sorry, as far as I know TW 5 is not supported by the plugin.

**Comment by ghost** [comment]
Bummer. Ok, thanks.
